"""render_go emits a compiling `package theme` with every token as a constant.

Lip Gloss v2 (charm.land/lipgloss/v2) constructs colours with
`lipgloss.Color("#hex") color.Color` and leaves light/dark detection to the
caller (`lipgloss.HasDarkBackground` + `lipgloss.LightDark`), so the generated
package exposes hex constants, two resolved palettes and a `ForBackground`
selector rather than any adaptive colour type.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from acceptrate.design.go import render_go
from acceptrate.design.tokens import Tokens, load_tokens

TOKENS_PATH = Path(__file__).resolve().parents[1] / "design" / "tokens.json"


def _render() -> tuple[Tokens, str]:
    tokens = load_tokens(TOKENS_PATH)
    return tokens, render_go(tokens)


def test_first_line_is_the_go_generated_marker() -> None:
    _, go = _render()

    assert go.splitlines()[0] == "// Code generated by acceptrate.design; DO NOT EDIT."
    assert "\npackage theme\n" in go


def test_imports_lipgloss_v2_and_image_color() -> None:
    _, go = _render()

    assert '"charm.land/lipgloss/v2"' in go
    assert '"image/color"' in go
    assert "github.com/charmbracelet" not in go


def test_every_palette_colour_is_a_hex_constant() -> None:
    tokens, go = _render()

    for name, hex_value in tokens.color.dark.items():
        assert f'Dark{_pascal(name)}Hex = "{hex_value}"' in _collapse(go)
    for name, hex_value in tokens.color.light.items():
        assert f'Light{_pascal(name)}Hex = "{hex_value}"' in _collapse(go)


def test_semantic_aliases_are_constants_referring_to_palette_constants() -> None:
    _, go = _render()
    collapsed = _collapse(go)

    assert "DarkAcceptedHex = DarkGreenHex" in collapsed
    assert "LightAcceptedHex = LightGreenHex" in collapsed
    assert "DarkRejectedHex = DarkRedHex" in collapsed
    assert "DarkMeasurementHex = DarkTealHex" in collapsed
    assert "LightCostHex = LightAmberHex" in collapsed


def test_glyphs_fonts_and_motion_are_constants() -> None:
    _, go = _render()
    collapsed = _collapse(go)

    assert 'GlyphAccepted = "●"' in collapsed
    assert 'GlyphRejected = "○"' in collapsed
    assert 'GlyphBonus = "◆"' in collapsed
    assert 'FontUI = "Geist"' in collapsed
    assert 'FontData = "Commit Mono"' in collapsed
    assert 'FontCapture = "JetBrains Mono"' in collapsed
    assert "SpringStiffness = 170.0" in collapsed
    assert "SpringDamping = 26.0" in collapsed
    assert "ReducedMotion = true" in collapsed


def test_palettes_resolve_through_lipgloss_color() -> None:
    _, go = _render()
    collapsed = _collapse(go)

    assert "type Palette struct {" in go
    assert "Ground color.Color" in collapsed
    assert "Accepted color.Color" in collapsed
    assert "func Dark() Palette {" in go
    assert "func Light() Palette {" in go
    assert "Ground: lipgloss.Color(DarkGroundHex)," in collapsed
    assert "Ground: lipgloss.Color(LightGroundHex)," in collapsed
    assert "Accepted: lipgloss.Color(LightAcceptedHex)," in collapsed
    assert "func ForBackground(isDark bool) Palette {" in go


@pytest.mark.skipif(shutil.which("gofmt") is None, reason="gofmt not on PATH")
def test_output_is_gofmt_clean(tmp_path: Path) -> None:
    _, go = _render()
    target = tmp_path / "theme_gen.go"
    target.write_text(go, encoding="utf-8")

    result = subprocess.run(["gofmt", "-l", str(target)], capture_output=True, text=True)

    assert result.returncode == 0, result.stderr
    assert result.stdout == "", f"gofmt would reformat:\n{result.stdout}"


def _pascal(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_"))


def _collapse(text: str) -> str:
    """Fold gofmt alignment whitespace so assertions do not depend on padding."""
    return " ".join(text.split())
