"""render_css emits the light palette on :root and the dark set under two selectors."""

from __future__ import annotations

import json
from pathlib import Path

from acceptrate.design.css import render_css
from acceptrate.design.tokens import Tokens, load_tokens

TOKENS_PATH = Path(__file__).resolve().parents[1] / "design" / "tokens.json"

DARK_ONLY = "#0E1319"
LIGHT_ONLY = "#E9ECF0"


def _render() -> tuple[Tokens, str]:
    tokens = load_tokens(TOKENS_PATH)
    return tokens, render_css(tokens)


def test_starts_with_the_generated_header() -> None:
    _, css = _render()

    assert css.startswith("/* Code generated by acceptrate.design; DO NOT EDIT. */")


def test_contains_every_colour_from_both_palettes() -> None:
    tokens, css = _render()

    for _, hex_value in tokens.color.dark.items() + tokens.color.light.items():
        assert hex_value in css


def test_light_set_is_on_root_and_dark_set_is_under_both_dark_selectors() -> None:
    _, css = _render()

    assert ":root {" in css
    assert "@media (prefers-color-scheme: dark)" in css
    assert ':root:not([data-theme="light"]) {' in css
    assert ':root[data-theme="dark"] {' in css
    assert css.count(DARK_ONLY) == 2, "dark colours appear once per dark block"
    assert css.count(LIGHT_ONLY) == 1, "light colours appear only on :root"


def test_light_block_precedes_the_dark_blocks() -> None:
    _, css = _render()

    assert css.index(LIGHT_ONLY) < css.index(DARK_ONLY)


def test_colour_names_are_kebab_cased_custom_properties() -> None:
    _, css = _render()

    assert "--color-surface-2: #F1F4F7;" in css
    assert "--color-ink-2: #AEBAC6;" in css
    assert "surface_2" not in css


def test_semantic_aliases_point_at_palette_properties() -> None:
    _, css = _render()

    assert "--color-accepted: var(--color-green);" in css
    assert "--color-rejected: var(--color-red);" in css
    assert "--color-measurement: var(--color-teal);" in css
    assert "--color-cost: var(--color-amber);" in css


def test_fonts_and_glyphs_are_custom_properties() -> None:
    _, css = _render()

    assert '--font-ui: "Geist";' in css
    assert '--font-data: "Commit Mono";' in css
    assert '--font-capture: "JetBrains Mono";' in css
    assert '--glyph-accepted: "●";' in css
    assert '--glyph-rejected: "○";' in css
    assert '--glyph-bonus: "◆";' in css


def test_motion_tokens_and_reduced_motion_query() -> None:
    _, css = _render()

    assert "--motion-spring-stiffness: 170;" in css
    assert "--motion-spring-damping: 26;" in css
    assert "--motion-reduced: 0;" in css
    assert "@media (prefers-reduced-motion: reduce)" in css
    assert "--motion-reduced: 1;" in css


def test_reduced_motion_query_is_omitted_when_disabled() -> None:
    data = json.loads(TOKENS_PATH.read_text())
    data["motion"]["reduced_motion"] = False

    css = render_css(Tokens.model_validate(data))

    assert "prefers-reduced-motion" not in css


def test_output_ends_with_a_single_newline() -> None:
    _, css = _render()

    assert css.endswith("}\n")
    assert not css.endswith("\n\n")
