// Code generated by acceptrate.design; DO NOT EDIT.

// Package theme is the "Instrument" design system for the TUI, generated
// from design/tokens.json. Lip Gloss v2 does not detect the terminal
// background itself; pick a palette with
// ForBackground(lipgloss.HasDarkBackground(os.Stdin, os.Stdout)).
package theme

import (
	"image/color"

	"charm.land/lipgloss/v2"
)

// Dark palette hex values.
const (
	DarkGroundHex   = "#0E1319"
	DarkSurfaceHex  = "#161D25"
	DarkSurface2Hex = "#1C252F"
	DarkSurface3Hex = "#253039"
	DarkInkHex      = "#E4EAF0"
	DarkInk2Hex     = "#AEBAC6"
	DarkMutedHex    = "#7D8C9B"
	DarkLineHex     = "#28323C"
	DarkLine2Hex    = "#36434F"
	DarkTealHex     = "#52B9C8"
	DarkAmberHex    = "#E3A44C"
	DarkGreenHex    = "#5CBE81"
	DarkRedHex      = "#E2697C"
)

// Light palette hex values.
const (
	LightGroundHex   = "#E9ECF0"
	LightSurfaceHex  = "#FCFDFE"
	LightSurface2Hex = "#F1F4F7"
	LightSurface3Hex = "#E3E8ED"
	LightInkHex      = "#141A21"
	LightInk2Hex     = "#44515E"
	LightMutedHex    = "#6E7C8A"
	LightLineHex     = "#CFD6DE"
	LightLine2Hex    = "#B9C3CD"
	LightTealHex     = "#0A6B76"
	LightAmberHex    = "#9A5A04"
	LightGreenHex    = "#2C7A4C"
	LightRedHex      = "#AE3448"
)

// Semantic aliases resolve to a palette colour per theme.
const (
	DarkAcceptedHex     = DarkGreenHex
	LightAcceptedHex    = LightGreenHex
	DarkRejectedHex     = DarkRedHex
	LightRejectedHex    = LightRedHex
	DarkMeasurementHex  = DarkTealHex
	LightMeasurementHex = LightTealHex
	DarkCostHex         = DarkAmberHex
	LightCostHex        = LightAmberHex
)

// Glyphs pair with colour so accept/reject never rely on colour alone.
const (
	GlyphAccepted = "●"
	GlyphRejected = "○"
	GlyphBonus    = "◆"
)

// Fonts are informational in a terminal; the capture face is what VHS records.
const (
	FontUI      = "Geist"
	FontData    = "Commit Mono"
	FontCapture = "JetBrains Mono"
)

// Spring tokens for Harmonica; ReducedMotion says to honour the user's preference.
const (
	SpringStiffness = 170.0
	SpringDamping   = 26.0
	ReducedMotion   = true
)

// Palette is one resolved colour set.
type Palette struct {
	Ground      color.Color
	Surface     color.Color
	Surface2    color.Color
	Surface3    color.Color
	Ink         color.Color
	Ink2        color.Color
	Muted       color.Color
	Line        color.Color
	Line2       color.Color
	Teal        color.Color
	Amber       color.Color
	Green       color.Color
	Red         color.Color
	Accepted    color.Color
	Rejected    color.Color
	Measurement color.Color
	Cost        color.Color
}

// Dark returns the dark Instrument palette.
func Dark() Palette {
	return Palette{
		Ground:      lipgloss.Color(DarkGroundHex),
		Surface:     lipgloss.Color(DarkSurfaceHex),
		Surface2:    lipgloss.Color(DarkSurface2Hex),
		Surface3:    lipgloss.Color(DarkSurface3Hex),
		Ink:         lipgloss.Color(DarkInkHex),
		Ink2:        lipgloss.Color(DarkInk2Hex),
		Muted:       lipgloss.Color(DarkMutedHex),
		Line:        lipgloss.Color(DarkLineHex),
		Line2:       lipgloss.Color(DarkLine2Hex),
		Teal:        lipgloss.Color(DarkTealHex),
		Amber:       lipgloss.Color(DarkAmberHex),
		Green:       lipgloss.Color(DarkGreenHex),
		Red:         lipgloss.Color(DarkRedHex),
		Accepted:    lipgloss.Color(DarkAcceptedHex),
		Rejected:    lipgloss.Color(DarkRejectedHex),
		Measurement: lipgloss.Color(DarkMeasurementHex),
		Cost:        lipgloss.Color(DarkCostHex),
	}
}

// Light returns the light Instrument palette.
func Light() Palette {
	return Palette{
		Ground:      lipgloss.Color(LightGroundHex),
		Surface:     lipgloss.Color(LightSurfaceHex),
		Surface2:    lipgloss.Color(LightSurface2Hex),
		Surface3:    lipgloss.Color(LightSurface3Hex),
		Ink:         lipgloss.Color(LightInkHex),
		Ink2:        lipgloss.Color(LightInk2Hex),
		Muted:       lipgloss.Color(LightMutedHex),
		Line:        lipgloss.Color(LightLineHex),
		Line2:       lipgloss.Color(LightLine2Hex),
		Teal:        lipgloss.Color(LightTealHex),
		Amber:       lipgloss.Color(LightAmberHex),
		Green:       lipgloss.Color(LightGreenHex),
		Red:         lipgloss.Color(LightRedHex),
		Accepted:    lipgloss.Color(LightAcceptedHex),
		Rejected:    lipgloss.Color(LightRejectedHex),
		Measurement: lipgloss.Color(LightMeasurementHex),
		Cost:        lipgloss.Color(LightCostHex),
	}
}

// ForBackground returns the palette for a dark or light terminal background.
func ForBackground(isDark bool) Palette {
	if isDark {
		return Dark()
	}
	return Light()
}
