"""Render tokens as CSS custom properties for the dashboard (Tailwind v4 token layer).

Light is the default on `:root`; the dark set is emitted twice, once under
`prefers-color-scheme: dark` (unless the page pins `data-theme="light"`) and
once under an explicit `data-theme="dark"`, so a user toggle wins over the OS.
"""

from __future__ import annotations

from acceptrate.design.tokens import Palette, Tokens

CSS_HEADER = "/* Code generated by acceptrate.design; DO NOT EDIT. */"
INDENT = "  "

DARK_SELECTOR_MEDIA = "@media (prefers-color-scheme: dark)"
DARK_SELECTOR_AUTO = ':root:not([data-theme="light"])'
DARK_SELECTOR_PINNED = ':root[data-theme="dark"]'
REDUCED_MOTION_MEDIA = "@media (prefers-reduced-motion: reduce)"


def render_css(tokens: Tokens) -> str:
    """Full stylesheet text; deterministic so `--check` can diff it byte for byte."""
    blocks = [
        CSS_HEADER,
        _rule(":root", _root_declarations(tokens)),
        _media(DARK_SELECTOR_MEDIA, DARK_SELECTOR_AUTO, _palette_declarations(tokens.color.dark)),
        _rule(DARK_SELECTOR_PINNED, _palette_declarations(tokens.color.dark)),
    ]
    if tokens.motion.reduced_motion:
        blocks.append(_media(REDUCED_MOTION_MEDIA, ":root", ("--motion-reduced: 1;",)))
    return "\n".join(blocks) + "\n"


def _root_declarations(tokens: Tokens) -> tuple[str, ...]:
    return (
        *_palette_declarations(tokens.color.light),
        *(
            f"--color-{role}: var(--color-{_kebab(name)});"
            for role, name in tokens.semantic.items()
        ),
        f'--font-ui: "{tokens.type.ui}";',
        f'--font-data: "{tokens.type.data}";',
        f'--font-capture: "{tokens.type.capture}";',
        f'--glyph-accepted: "{tokens.glyph.accepted}";',
        f'--glyph-rejected: "{tokens.glyph.rejected}";',
        f'--glyph-bonus: "{tokens.glyph.bonus}";',
        f"--motion-spring-stiffness: {_number(tokens.motion.spring.stiffness)};",
        f"--motion-spring-damping: {_number(tokens.motion.spring.damping)};",
        "--motion-reduced: 0;",
    )


def _palette_declarations(palette: Palette) -> tuple[str, ...]:
    return tuple(f"--color-{_kebab(name)}: {hex_value};" for name, hex_value in palette.items())


def _rule(selector: str, declarations: tuple[str, ...], depth: int = 0) -> str:
    pad = INDENT * depth
    body = "\n".join(f"{pad}{INDENT}{line}" for line in declarations)
    return f"{pad}{selector} {{\n{body}\n{pad}}}"


def _media(query: str, selector: str, declarations: tuple[str, ...]) -> str:
    return f"{query} {{\n{_rule(selector, declarations, depth=1)}\n}}"


def _kebab(name: str) -> str:
    return name.replace("_", "-")


def _number(value: float) -> str:
    return str(int(value)) if value.is_integer() else str(value)
