"""Render tokens as a Go `package theme` for the Bubble Tea TUI.

Verified against pkg.go.dev/charm.land/lipgloss/v2 (v2.0.6): colours are
plain `image/color.Color` values made with `lipgloss.Color("#hex")`, and the
library does not pick light/dark for you, so the package exposes hex
constants, two resolved palettes and `ForBackground(isDark)` for the caller
to feed with `lipgloss.HasDarkBackground(os.Stdin, os.Stdout)`.

Output is gofmt-clean by construction: every aligned column is padded here.
"""

from __future__ import annotations

from acceptrate.design.tokens import Palette, Tokens

GO_HEADER = "// Code generated by acceptrate.design; DO NOT EDIT."
LIPGLOSS_IMPORT = "charm.land/lipgloss/v2"
THEMES = ("Dark", "Light")

FONT_CONST_NAMES = {"ui": "FontUI", "data": "FontData", "capture": "FontCapture"}
GLYPH_CONST_NAMES = {
    "accepted": "GlyphAccepted",
    "rejected": "GlyphRejected",
    "bonus": "GlyphBonus",
}

PACKAGE_DOC = """\
// Package theme is the "Instrument" design system for the TUI, generated
// from design/tokens.json. Lip Gloss v2 does not detect the terminal
// background itself; pick a palette with
// ForBackground(lipgloss.HasDarkBackground(os.Stdin, os.Stdout))."""


def render_go(tokens: Tokens) -> str:
    """Full source text of tui/theme/theme_gen.go."""
    sections = (
        GO_HEADER,
        "",
        PACKAGE_DOC,
        "package theme",
        "",
        "import (",
        '\t"image/color"',
        "",
        f'\t"{LIPGLOSS_IMPORT}"',
        ")",
        "",
        _const_block("Dark palette hex values.", _hex_rows("Dark", tokens.color.dark)),
        _const_block("Light palette hex values.", _hex_rows("Light", tokens.color.light)),
        _const_block(
            "Semantic aliases resolve to a palette colour per theme.", _alias_rows(tokens)
        ),
        _const_block(
            "Glyphs pair with colour so accept/reject never rely on colour alone.",
            [(GLYPH_CONST_NAMES[k], _quote(v)) for k, v in tokens.glyph.model_dump().items()],
        ),
        _const_block(
            "Fonts are informational in a terminal; the capture face is what VHS records.",
            [(FONT_CONST_NAMES[k], _quote(v)) for k, v in tokens.type.model_dump().items()],
        ),
        _const_block(
            "Spring tokens for Harmonica; ReducedMotion says to honour the user's preference.",
            [
                ("SpringStiffness", repr(float(tokens.motion.spring.stiffness))),
                ("SpringDamping", repr(float(tokens.motion.spring.damping))),
                ("ReducedMotion", "true" if tokens.motion.reduced_motion else "false"),
            ],
        ),
        _palette_struct(tokens),
        *(_palette_func(theme, tokens) for theme in THEMES),
        _for_background_func(),
    )
    return "\n".join(sections)


def _hex_rows(theme: str, palette: Palette) -> list[tuple[str, str]]:
    return [(f"{theme}{_pascal(name)}Hex", _quote(value)) for name, value in palette.items()]


def _alias_rows(tokens: Tokens) -> list[tuple[str, str]]:
    return [
        (f"{theme}{_pascal(role)}Hex", f"{theme}{_pascal(name)}Hex")
        for role, name in tokens.semantic.items()
        for theme in THEMES
    ]


def _palette_field_names(tokens: Tokens) -> tuple[str, ...]:
    return tuple(_pascal(name) for name in (*tokens.color.dark.model_dump(), *tokens.semantic))


def _palette_struct(tokens: Tokens) -> str:
    rows = _aligned([(name, "color.Color") for name in _palette_field_names(tokens)], sep=" ")
    body = "\n".join(f"\t{row}" for row in rows)
    return f"// Palette is one resolved colour set.\ntype Palette struct {{\n{body}\n}}\n"


def _palette_func(theme: str, tokens: Tokens) -> str:
    rows = _aligned(
        [
            (f"{name}:", f"lipgloss.Color({theme}{name}Hex),")
            for name in _palette_field_names(tokens)
        ],
        sep=" ",
    )
    body = "\n".join(f"\t\t{row}" for row in rows)
    return (
        f"// {theme} returns the {theme.lower()} Instrument palette.\n"
        f"func {theme}() Palette {{\n\treturn Palette{{\n{body}\n\t}}\n}}\n"
    )


def _for_background_func() -> str:
    return (
        "// ForBackground returns the palette for a dark or light terminal background.\n"
        "func ForBackground(isDark bool) Palette {\n"
        "\tif isDark {\n\t\treturn Dark()\n\t}\n\treturn Light()\n}\n"
    )


def _const_block(comment: str, rows: list[tuple[str, str]]) -> str:
    body = "\n".join(f"\t{row}" for row in _aligned(rows, sep=" = "))
    return f"// {comment}\nconst (\n{body}\n)\n"


def _aligned(rows: list[tuple[str, str]], sep: str) -> list[str]:
    """Pad the left column so gofmt has nothing to change."""
    width = max(len(left) for left, _ in rows)
    return [f"{left:<{width}}{sep}{right}" for left, right in rows]


def _pascal(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_"))


def _quote(value: str) -> str:
    return f'"{value}"'
